### ISSUE TITLE
InAppPurchaseData no non-static method with name

### ISSUE THREAD

**Issue by AdCCooN** [EvilMindDevs/hms-unity-plugin#120]
Hello guys

I am using HMS.UnityPluginFor2019And2020v1.2.0 and Unity 2019.4.4f1

So I have  a problem with the InAppPurchaseData object that I am trying to create using the string obtained from the  PurchaseResultInfo or ObtainOwnedPurchases requests.

More exactly, I have problem with **AutoRenewing** and **SubValid** Properties for which I obtain a java.lang.NoSuchMethodError -> 

java.lang.NoSuchMethodError: no non-static method with name='getSubValid' signature='()Z' in class Lcom.huawei.hms.iap.entity.InAppPurchaseData;
	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:229)
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:219)
	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
  at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AndroidReflection.GetMethodMember (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AndroidJNIHelper.GetMethodID (System.IntPtr javaClass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine._AndroidJNIHelper.GetMethodID[ReturnType] (System.IntPtr jclass, System.String methodName, System.Object[] args, System.Boolean isStatic) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AndroidJNIHelper.GetMethodID[ReturnType] (System.IntPtr jclass, System.String methodName, System.Object[] args, System.Boolean isStatic) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AndroidJavaObject._Call[ReturnType] (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AndroidJavaObject.Call[ReturnType] (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0 
  at HuaweiMobileServices.Utils.JavaObjectWrapper.Call[T] (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0 
  at HuaweiMobileServices.IAP.InAppPurchaseData.get_SubValid () [0x00000] in <00000000000000000000000000000000>:0 
  at HuaweiPurchaseReceipt..ctor (HuaweiMobileServices.IAP.InAppPurchaseData purchaseData) [0x00000] in <00000000000000000000000000000000>:0 
  at IAPHuaweiManager+<>c__DisplayClass14_0.<CheckAndConsumePendingConsumableProductsTransactions>b__2 () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityMainThreadDispatcher+<ActionWrapper>d__5.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.MonoBehaviour.StartCoroutine (System.Collections.IEnumerator routine) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityMainThreadDispatcher+<>c__DisplayClass2_0.<Enqueue>b__0 () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityMainThreadDispatcher.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Logger:Error(String)
<>c__DisplayClass14_0:<CheckAndConsumePendingConsumableProductsTransactions>b__2()
System.Action:Invoke()
<ActionWrapper>d__5:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<>c__DisplayClass2_0:<Enqueue>b__0()
System.Action:Invoke()
UnityMainThreadDispatcher:Update()

**Comment by sametguzeldev** [comment]
Hello there. I think we have some old files inside the HMS.UnityPluginFor2019And2020v1.2.0 which we'll fix soon. Can you download the project(you can follow the image) then import all of the files then try again ?
![image](https://user-images.githubusercontent.com/6827857/109078438-61439a80-770e-11eb-88b8-04ba7ac086d9.png)

**Comment by AdCCooN** [comment]
I've added the DLL that is currently in the git project and it solved the exception for **SubValid** but there is still an exception for **AutoRenewing** so you guys could take a look also on that for the next update.

I will avoid the access to that property but this should be marked to be fixed. 

Thank you!

**Comment by sametguzeldev** [comment]
> I've added the DLL that is currently in the git project and it solved the exception for **SubValid** but there is still an exception for **AutoRenewing** so you guys could take a look also on that for the next update.
> 
> I will avoid the access to that property but this should be marked to be fixed.
> 
> Thank you!

Yes you are right. Currently there is a problem with AutoRenewing property. I've just fixed that as well. I'll be pushing as commit or PR soon. You can follow that up here.
https://github.com/EvilMindDevs/hms-sdk-unity/

**Comment by AdCCooN** [comment]
> > I've added the DLL that is currently in the git project and it solved the exception for **SubValid** but there is still an exception for **AutoRenewing** so you guys could take a look also on that for the next update.
> > I will avoid the access to that property but this should be marked to be fixed.
> > Thank you!
> 
> Yes you are right. Currently there is a problem with AutoRenewing property. I've just fixed that as well. I'll be pushing as commit or PR soon. You can follow that up here. But you would have to build the solution yourself and get the dll inside :)
> https://github.com/EvilMindDevs/hms-sdk-unity/

Thank you @sametguzeldev , appreciate!

**Comment by sametguzeldev** [comment]
You are welcome :) You can check https://github.com/EvilMindDevs/hms-sdk-unity/  for the AutoRenewing Fix. It is live atm.
