### ISSUE TITLE
[Game Service] Calling IArchiveClient methods can cause error

### ISSUE THREAD

**Issue by Whaledevelop** [EvilMindDevs/hms-unity-plugin#267]
Hello! 

Error stack trace
`E Unity   : AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='getStatus' signature='()Ljava/lang/Object;' in class Lcom.huawei.hms.common.ApiException;
E Unity   : java.lang.NoSuchMethodError: no non-static method with name='getStatus' signature='()Ljava/lang/Object;' in class Lcom.huawei.hms.common.ApiException;
E Unity   : 	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:229)
E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
E Unity   : 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
E Unity   : 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
E Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:102)
E Unity   : 	at android.os.Looper.loop(Looper.java:201)
E Unity   : 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
E Unity   :   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <000000000000000000000000`

This can happen when saving, updating or loading, when calling some IArchiveClient methods - AddArchive, UpdateArchive or GetArchiveSummaryList. On any call : may be successfully saved 2 times, on the third it may fail. May occur on first call. Maybe ten. I did not find patterns. After the error has occurred once, all calls to IArchiveClient result in the same error. Only deleting progress and reinstalling the game helps.
I tried it both in my implementation and in the GameDemo demo scene with attached demo scripts from plugin.

Thanks!

**Comment by alihan98ersoy** [comment]
Hello

We are investigating the issue.

Thanks

**Comment by alihan98ersoy** [comment]
Hello

I tested with the new version and I couldn't get the same error. If you want I can confirm that the old version has the issue and with the new version, we fixed the issue. Which version are you using?
