### ISSUE TITLE
[Crash]  Launch App try Exception

### ISSUE THREAD

**Issue by tdouguo** [EvilMindDevs/hms-unity-plugin#282]
2022-02-11 11:39:27 27845-27909/? E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.huawei.agconnect.auth.AGConnectAuth
java.lang.ClassNotFoundException: com.huawei.agconnect.auth.AGConnectAuth
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.access$600(Unknown Source:0)
	at com.unity3d.player.UnityPlayer$g$1.handleMessage(Unknown Source:150)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:213)
	at com.unity3d.player.UnityPlayer$g.run(Unknown Source:20)
Caused by: java.lang.ClassNotFoundException: com.huawei.agconnect.auth.AGConnectAuth
	... 8 more
  at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00000] 
2022-02-11 11:39:27 27845-27909/? E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.huawei.agconnect.crash.AGConnectCrash
java.lang.ClassNotFoundException: com.huawei.agconnect.crash.AGConnectCrash
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.access$600(Unknown Source:0)
	at com.unity3d.player.UnityPlayer$g$1.handleMessage(Unknown Source:150)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:213)
	at com.unity3d.player.UnityPlayer$g.run(Unknown Source:20)
Caused by: java.lang.ClassNotFoundException: com.huawei.agconnect.crash.AGConnectCrash
	... 8 more
  at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x0

**Comment by alihan98ersoy** [comment]
Hello,
Did you enable the auth service in the plugin?
Huawei>Kit Settings>Kits
![resim](https://user-images.githubusercontent.com/39373386/153551963-1a57d613-1017-4a96-95dc-9ef76e254d6d.png)
