### ISSUE TITLE
Repetitive crash at app start on GenericBridge.launchShow

### ISSUE THREAD

**Issue by ksnnacar** [EvilMindDevs/hms-unity-plugin#311]
Hello there, we're having this issue on app start. Using v2.2.1 with unity 2019.4.32f1 and proguard disabled.  Any helps are appreciated.

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.game.huawei/org.m0skit0.android.hms.unity.activity.NativeBridgeActivity}

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1731)
       at android.app.Activity.startActivityForResult(Activity.java:5362)
       at android.app.Activity.startActivityForResult(Activity.java:5303)
       at org.m0skit0.android.hms.unity.GenericBridge.launchShow(GenericBridge.java:27)
       at org.m0skit0.android.hms.unity.activity.NativeBridgeActivity.onCreate(NativeBridgeActivity.java:46)
       at android.app.Activity.performCreate(Activity.java:8085)
       at android.app.Activity.performCreate(Activity.java:8073)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3870)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4076)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8349)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by alihan98ersoy** [comment]
Hello, 
may I get the full logs? And are you testing with HMS or non-HMS devices?

**Comment by ksnnacar** [comment]
> Hello, may I get the full logs? And are you testing with HMS or non-HMS devices?

Hi, this is from crashlytics report on a live game on huawei store,  Crashes seem to be mostly on Huawei MatePad T8 KOB2-W09. Android 10. I'll also submit more detailed reports if I can get one.

**Comment by alihan98ersoy** [comment]
Hello,

We will release the solution to the problem with the next version that we will release in mid-June.

**Comment by alihan98ersoy** [comment]
We thought of the solution theoretically, but we did not implement it due to the risks, as we did not have the opportunity to test it. So far, we have not encountered the same problem, or we have not come across anyone who has faced the same problem. Does the problem persist?
