### ISSUE TITLE
AndroidJavaException: java.lang.ClassNotFoundException: com.huawei.hms.jos.AppParams

### ISSUE THREAD

**Issue by VeljkoLukic** [EvilMindDevs/hms-unity-plugin#335]
When I call ShowAchievements I receive `AndroidJavaException: java.lang.ClassNotFoundException: com.huawei.hms.jos.AppParams` error

`java.lang.ClassNotFoundException: com.huawei.hms.jos.AppParams
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:219)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)`

**Comment by alihan98ersoy** [comment]
Did you enable game service from the kit settings?
![resim](https://user-images.githubusercontent.com/39373386/176705715-4489c9e8-9944-443e-8d40-000453a4b8fb.png)

if yes can you disable and enable it again?

**Comment by VeljkoLukic** [comment]
The issue was solved by re-enabling all the services on the huawei console
