### ISSUE TITLE
I can't sign-in from AccountDemo.unity

### ISSUE THREAD

**Issue by kimtat** [EvilMindDevs/hms-unity-plugin#40]
I just create a new project, then import the plugin. Then, update the agconnect-services.json and 
AndroidManifest.xml. Is there any missing? 

2020-07-03 11:16:36.055 13873-13873/com.kingyou.testhms I/Unity: [HMS]: Sign in failedException of type 'HuaweiMobileServices.Utils.HMSException' was thrown. 
    AccountDemoManager:OnLoginFailure(HMSException)
    System.Action`1:Invoke(T)
    System.Action`1:Invoke(T)
    System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
    UnityEngine.AndroidJavaProxy:Invoke(String, Object[])
    UnityEngine._AndroidJNIHelper:InvokeJavaProxyMethod(AndroidJavaProxy, IntPtr, IntPtr)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-07-03 11:16:36.072 14222-14304/? I/InAppTransport: [I/HMSCore/InAppTransport 14222:45904 :95] In-App Request, uri: hwid.inner.getServiceToken, clientIdentity: {appId: 10132067, hostAppID: 10132067, packageName: com.huawei.hwid, sdkVersion: 0, uid: 0, transactionId: , apiLevel: 0, uri: null, kitSdkVersion: 0}
2020-07-03 11:16:36.074 13873-13873/com.kingyou.testhms E/Unity: UnityException: get_isActiveAndEnabled can only be called from the main thread.
    Constructors and field initializers will be executed from the loading thread when loading a scene.
    Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
      at UnityEngine.UI.Graphic.SetVerticesDirty () [0x00000] in <00000000000000000000000000000000>:0 
      at UnityEngine.UI.Text.set_text (System.String value) [0x00000] in <00000000000000000000000000000000>:0 
      at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
      at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
      at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <00000000000000000000000000000000>:0 
      at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, S

**Comment by kimtat** [comment]
The situation is when I click sign-in. The screen flash to (new intent)? for less than 1 second, then return to sign-in button screen. 
I try to list out the possible reasons of failure. 

2020-07-03 17:07:42.018 5963-5963/? W/KgViewUtils: setViewAlpha for null View
    java.lang.Exception
        at com.huawei.keyguard.view.KgViewUtils.setViewAlpha(KgViewUtils.java:224)
        at com.android.keyguard.hwlockscreen.magazine.MagazineDetailView.resetToTimeView(MagazineDetailView.java:705)
        at com.android.keyguard.hwlockscreen.magazine.MagazineDetailView.setLiftReset(MagazineDetailView.java:732)
        at com.android.keyguard.hwlockscreen.magazine.MagazineDetailView.setLiftReset(MagazineDetailView.java:727)
        at com.android.keyguard.hwlockscreen.HwKeyguardBottomArea.handleMessage(HwKeyguardBottomArea.java:1701)
        at com.huawei.keyguard.events.AppHandler$MessageCallback.handleMessage(AppHandler.java:110)
        at com.huawei.keyguard.events.AppHandler$MessageCallback.handleMessage(AppHandler.java:102)
        at com.huawei.keyguard.events.AppHandler.sendImmediateMessage(AppHandler.java:135)
        at com.huawei.keyguard.events.AppHandler.sendImmediateMessage(AppHandler.java:158)
        at com.huawei.keyguard.HwKeyguardUpdateMonitor.setKeyguardViewState(HwKeyguardUpdateMonitor.java:698)
        at com.huawei.keyguard.HwKeyguardUpdateMonitor.setKeyguardViewState(HwKeyguardUpdateMonitor.java:639)
        at com.android.systemui.keyguard.HwKeyguardViewMediator.handleSetOccluded(HwKeyguardViewMediator.java:274)
        at com.android.systemui.keyguard.KeyguardViewMediator$5.handleMessage(KeyguardViewMediator.java:1914)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by m0skit0** [comment]
Did you fill the relevant information as explained in step 3 - Configure your Manifest in the README?

**Comment by kimtat** [comment]
Yes. I did change the app_id, cp_id and package_name. And also, i replace the agconnect-services.json file in the project.

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.unity3d.player" xmlns:tools="http://schemas.android.com/tools" android:installLocation="preferExternal">
  <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true" />
  <application android:theme="@style/UnityThemeSelector" android:icon="@mipmap/app_icon" android:label="@string/app_name">
    <activity android:name="com.unity3d.player.UnityPlayerActivity" android:label="@string/app_name">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
    </activity>
    <meta-data android:name="com.huawei.hms.client.appid" android:value="appid=102487871" />
    <meta-data android:name="com.huawei.hms.client.cpid" android:value="cpid=80852000000119997" />
    <meta-data android:name="com.huawei.hms.version" android:value="2.6.1" />
    <provider android:name="com.huawei.hms.update.provider.UpdateProvider" android:authorities="com.kingyou.testhms.hms.update.provider" android:exported="false" android:grantUriPermissions="true" />
    <provider android:name="com.huawei.updatesdk.fileprovider.UpdateSdkFileProvider" android:authorities="com.kingyou.testhms.updateSdk.fileProvider" android:exported="false" android:grantUriPermissions="true" />
  </application>
  <uses-permission android:name="com.huawei.appmarket.service.commondata.permission.GET_COMMON_DATA" />
  <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
  <uses-permission android:name="android.permission.READ_PHONE_STATE" />
</manifest>

**Comment by m0skit0** [comment]
Thanks. Can you please specify your Unity version and if IL2CPP is selected?

**Comment by kimtat** [comment]
unity 2019.4.1f1 personal
IL2CPP selected
HMS.Unity.Plugin.for.2019.v1.1.2
EMUI 9.1.0 from Huawei mediapad M5 pro

**Comment by kimtat** [comment]
When I press the "Log In" button, prompt following exception and the login intent didn't come out. 
setViewAlpha for null View
java.lang.Exception
        at com.huawei.keyguard.view.KgViewUtils.setViewAlpha(KgViewUtils.java:224),
        at com.android.keyguard.hwlockscreen.magazine.MagazineDetailView.resetToTimeView(MagazineDetailView.java:705)

then, 
[HMS]: Sign in failed, Exception of type 'HuaweiMobileServices.Utils.HMSException' was thrown.

then 
E/Unity: UnityException: get_isActiveAndEnabled can only be called from the main thread.
    Constructors and field initializers will be executed from the loading thread when loading a scene.

**Comment by EtsaiDev** [comment]
I forgot to add the SHA-256 key in Project Settings. Maybe this helps you.

**Comment by kimtat** [comment]
It works! Exactly. Sorry and Thank you!
